import React from 'react'
import { View, Text } from 'react-native'
import Search from '.'

export default () => {
  return (
    <React.Fragment>
      <Search>
        <View>
          <Text>测试展示</Text>
        </View>
        <View>
          <Text>测试展示</Text>
        </View>
        <View>
          <Text>测试展示</Text>
        </View>
        <View>
          <Text>测试展示</Text>
        </View>
        <View>
          <Text>测试展示</Text>
        </View>
        <View>
          <Text>测试展示</Text>
        </View>
        <View>
          <Text>测试展示</Text>
        </View>
        <View>
          <Text>测试展示</Text>
        </View>
        <View>
          <Text>测试展示</Text>
        </View>
        <View>
          <Text>测试展示</Text>
        </View>
        <View>
          <Text>测试展示</Text>
        </View>
        <View>
          <Text>测试展示</Text>
        </View>
        <View>
          <Text>测试展示</Text>
        </View>
        <View>
          <Text>测试展示</Text>
        </View>
        <View>
          <Text>测试展示</Text>
        </View>
        <View>
          <Text>测试展示</Text>
        </View>
        <View>
          <Text>测试展示</Text>
        </View>
        <View>
          <Text>测试展示</Text>
        </View>
        <View>
          <Text>测试展示</Text>
        </View>
        <View>
          <Text>测试展示</Text>
        </View>
        <View>
          <Text>测试展示</Text>
        </View>
        <View>
          <Text>测试展示</Text>
        </View>
        <View>
          <Text>测试展示</Text>
        </View>
        <View>
          <Text>测试展示</Text>
        </View>
      </Search>
    </React.Fragment>
  )
}
